name: CI/CD ASP.NET MVC (Full .NET Framework) to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Descargar el código desde GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar MSBuild en el runner
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # 3. Restaurar paquetes NuGet
      - name: Restore NuGet packages
        run: nuget restore aspnet-get-started.sln

      # 4. Compilar en Release y publicar en carpeta "publish"
      - name: Publish web app
        run: msbuild aspnet-get-started.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl="${{ github.workspace }}\publish"

      # 5. Desplegar directamente la carpeta "publish" a Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: myAppVsc # Cambia por el nombre exacto de tu App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}\publish


