name: CI/CD ASP.NET MVC (Full .NET Framework) to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore aspnet-get-started.sln

      - name: Build and publish web project
        run: msbuild "aspnet-get-started/aspnet-get-started.csproj" ^
          /p:Configuration=Release ^
          /p:DeployOnBuild=true ^
          /p:WebPublishMethod=FileSystem ^
          /p:PublishUrl="${{ github.workspace }}/publish"

      - name: List publish folder
        run: dir "${{ github.workspace }}/publish"

      - name: Check for web.config
        run: |
          if (-not (Test-Path "${{ github.workspace }}/publish/web.config")) {
            Write-Error "Publish failed: web.config not found in publish folder."
          }

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: myAppVsc
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish











