name: CI/CD ASP.NET MVC (Full .NET Framework) to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore aspnet-get-started.sln

      - name: Find .csproj file
        id: findproj
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
          if (-not $proj) { Write-Error "No .csproj file found" }
          echo "PROJECT_PATH=$($proj.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Found project: $($proj.FullName)"

      - name: Build and publish web project
        run: msbuild "${{ env.PROJECT_PATH }}" /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl="${{ github.workspace }}\publish"

      - name: Verify publish folder
        run: |
          if (-not (Test-Path "${{ github.workspace }}\publish\web.config")) {
            Write-Error "Publish failed: web.config not found in publish folder."
          }
          dir "${{ github.workspace }}\publish"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: myAppVsc # Cambia por el nombre exacto de tu Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish









